name: onai_docs
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5
  mask_text_input_formatter: ^2.4.0
  intl: ^0.20.2
  dio: ^5.1.1
  l: ^3.2.0
  shared_preferences: ^2.1.0
  pure: ^0.2.0
  drift: ^2.7.0
  path: ^1.8.2
  path_provider: ^2.0.14
  package_info_plus: ^8.3.0
  stack_trace: ^1.11.0
  stream_bloc: ^0.5.3
  meta: ^1.8.0
  flutter_bloc: ^8.1.3
  internet_connection_checker: ^1.0.0+1
  bloc_concurrency: ^0.2.2
  rxdart: ^0.27.7
  freezed_annotation: ^2.2.0
  json_serializable: ^6.6.1
  json_annotation: ^4.8.0
  pretty_dio_logger: ^1.3.1
  pull_to_refresh: ^2.0.0
  auto_route: ^10.0.1
  loader_overlay: ^2.2.0
  shimmer: ^3.0.0
  provider: ^6.0.5
  flutter_inappwebview: ^6.1.5
  readmore: ^3.0.0

# dependency_overrides:
#   analyzer: ^6.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  freezed: ^2.3.2
  flutter_lints: ^2.0.1
  lint: ^2.0.1
  drift_dev: ^2.7.0
  auto_route_generator: ^10.0.1




flutter:
  generate: true
  uses-material-design: true


  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/


  fonts:
  - family: Nunito
    fonts:
      - asset: assets/fonts/Nunito/Nunito-ExtraLight.ttf
      - asset: assets/fonts/Nunito/Nunito-ExtraLightItalic.ttf
      - asset: assets/fonts/Nunito/Nunito-Light.ttf
      - asset: assets/fonts/Nunito/Nunito-LightItalic.ttf
      - asset: assets/fonts/Nunito/Nunito-Regular.ttf
      - asset: assets/fonts/Nunito/Nunito-Italic.ttf
      - asset: assets/fonts/Nunito/Nunito-Medium.ttf
      - asset: assets/fonts/Nunito/Nunito-MediumItalic.ttf
      - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
      - asset: assets/fonts/Nunito/Nunito-SemiBoldItalic.ttf
      - asset: assets/fonts/Nunito/Nunito-Bold.ttf
      - asset: assets/fonts/Nunito/Nunito-BoldItalic.ttf
      - asset: assets/fonts/Nunito/Nunito-ExtraBold.ttf
      - asset: assets/fonts/Nunito/Nunito-ExtraBoldItalic.ttf
      - asset: assets/fonts/Nunito/Nunito-Black.ttf
      - asset: assets/fonts/Nunito/Nunito-BlackItalic.ttf
